package com.ising99.wkis.domain;

import com.ising99.wkis.common.WebConfig;

import java.io.Serializable;

public class Os implements Serializable {
    public static final int AREA_CN = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os.name
     *
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os.version
     *
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os.md5
     *
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    private String md5;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os.size
     *
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    private Integer size;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os.url
     *
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os.code
     *
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column os.description
     *
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    private String description;

    private long utc;

    private long previous_utc;

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    private int type;

    private String otaUrl;

    public void setOtaUrl(String otaUrl) {
        this.otaUrl = otaUrl;
    }

    public long getUtc() {
        return utc;
    }

    public void setUtc(long utc) {
        this.utc = utc;
    }

    public long getPreviousUtc() {
        return previous_utc;
    }

    public void setPreviousUtc(long previousUtc) {
        this.previous_utc = previousUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os.name
     *
     * @return the value of os.name
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os.name
     *
     * @param name the value for os.name
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os.version
     *
     * @return the value of os.version
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os.version
     *
     * @param version the value for os.version
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os.md5
     *
     * @return the value of os.md5
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os.md5
     *
     * @param md5 the value for os.md5
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os.size
     *
     * @return the value of os.size
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os.size
     *
     * @param size the value for os.size
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public void setSize(Integer size) {
        this.size = size;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os.url
     *
     * @return the value of os.url
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public String getUrl() {
        if (this.url != null && this.url.length() != 0) {
            this.url = otaUrl + this.url;
        }
        return this.url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os.url
     *
     * @param url the value for os.url
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os.code
     *
     * @return the value of os.code
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os.code
     *
     * @param code the value for os.code
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column os.description
     *
     * @return the value of os.description
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column os.description
     *
     * @param description the value for os.description
     * @mbggenerated Fri May 23 11:54:24 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}