package com.ising99.wkis.domain;


public class PlayerTheme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme.id
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Integer id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme.title
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme.bg_img
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String bgimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme.selected_img
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String selectedimg;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player_theme.id
     *
     * @return the value of t_player_theme.id
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player_theme.id
     *
     * @param id the value for t_player_theme.id
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player_theme.title
     *
     * @return the value of t_player_theme.title
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player_theme.title
     *
     * @param title the value for t_player_theme.title
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player_theme.bg_img
     *
     * @return the value of t_player_theme.bg_img
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public String getBgimg() {
        return bgimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player_theme.bg_img
     *
     * @param bgimg the value for t_player_theme.bg_img
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public void setBgimg(String bgimg) {
        this.bgimg = bgimg == null ? null : bgimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player_theme.selected_img
     *
     * @return the value of t_player_theme.selected_img
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public String getSelectedimg() {
        return selectedimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player_theme.selected_img
     *
     * @param selectedimg the value for t_player_theme.selected_img
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public void setSelectedimg(String selectedimg) {
        this.selectedimg = selectedimg == null ? null : selectedimg.trim();
    }
}