package com.ising99.wkis.domain;

public class PlayerThemeMusic {

    public String getSongid() {
        return songid;
    }

    public void setSongid(String songid) {
        this.songid = songid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSinger() {
        return singer;
    }

    public void setSinger(String singer) {
        this.singer = singer;
    }

    public String getSingerid() {
        return singerid;
    }

    public void setSingerid(String singerid) {
        this.singerid = singerid;
    }

    public Boolean getIsis9() {
        return isis9;
    }

    public void setIsis9(Boolean isis9) {
        this.isis9 = isis9;
    }


    public Integer getLanguagecode() {
        return languagecode;
    }

    public void setLanguagecode(Integer languagecode) {
        this.languagecode = languagecode;
    }

    public String getSpell() {
        return spell;
    }

    public void setSpell(String spell) {
        this.spell = spell;
    }

    public Integer getScene1() {
        return scene1;
    }

    public void setScene1(Integer scene1) {
        this.scene1 = scene1;
    }

    public Integer getScene2() {
        return scene2;
    }

    public void setScene2(Integer scene2) {
        this.scene2 = scene2;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.song_id
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String songid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.name
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.singer
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String singer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.singer_id
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String singerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.is_is9
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Boolean isis9;

    public Integer getSingertype() {
        return singertype;
    }

    public void setSingertype(Integer singertype) {
        this.singertype = singertype;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.type
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Integer singertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.languagecode
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Integer languagecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.spell
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private String spell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.scene1
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Integer scene1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.scene2
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Integer scene2;

}