package com.ising99.wkis.dao;

import com.ising99.wkis.parameter.PayinfoByUrlParam;
import org.springframework.stereotype.Repository;

@Repository
public interface PayinfoByUrlMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payinfbyurl
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    int insert(PayinfoByUrlParam record);

}