package com.ising99.wkis.dao;

import com.ising99.wkis.parameter.TVAppDownloadInfoParam;
import org.springframework.stereotype.Repository;

@Repository
public interface TVAppDownloadInfoMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvapp_download_info
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    int insert(TVAppDownloadInfoParam record);


}