package com.ising99.wkis.parameter;

import java.math.BigDecimal;
import java.util.Date;

public class PayinfoByUrlParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.ID
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.URL
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.IP
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.QUERYSTRING
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String querystring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.CREATETIME
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.LOACLORDERNO
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String loaclorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.MERCHANTNO
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String merchantno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.PAYSTATUS
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.PAYMONEY
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private BigDecimal paymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.MD5STR
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String md5str;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.COMMODITY
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.COMCOUNT
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private Integer comcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payinfbyurl.COMPRICE
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    private BigDecimal comprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.ID
     *
     * @return the value of t_payinfbyurl.ID
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.ID
     *
     * @param id the value for t_payinfbyurl.ID
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.URL
     *
     * @return the value of t_payinfbyurl.URL
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.URL
     *
     * @param url the value for t_payinfbyurl.URL
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.IP
     *
     * @return the value of t_payinfbyurl.IP
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.IP
     *
     * @param ip the value for t_payinfbyurl.IP
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.QUERYSTRING
     *
     * @return the value of t_payinfbyurl.QUERYSTRING
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getQuerystring() {
        return querystring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.QUERYSTRING
     *
     * @param querystring the value for t_payinfbyurl.QUERYSTRING
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setQuerystring(String querystring) {
        this.querystring = querystring == null ? null : querystring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.CREATETIME
     *
     * @return the value of t_payinfbyurl.CREATETIME
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.CREATETIME
     *
     * @param createtime the value for t_payinfbyurl.CREATETIME
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.LOACLORDERNO
     *
     * @return the value of t_payinfbyurl.LOACLORDERNO
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getLoaclorderno() {
        return loaclorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.LOACLORDERNO
     *
     * @param loaclorderno the value for t_payinfbyurl.LOACLORDERNO
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setLoaclorderno(String loaclorderno) {
        this.loaclorderno = loaclorderno == null ? null : loaclorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.MERCHANTNO
     *
     * @return the value of t_payinfbyurl.MERCHANTNO
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getMerchantno() {
        return merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.MERCHANTNO
     *
     * @param merchantno the value for t_payinfbyurl.MERCHANTNO
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setMerchantno(String merchantno) {
        this.merchantno = merchantno == null ? null : merchantno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.PAYSTATUS
     *
     * @return the value of t_payinfbyurl.PAYSTATUS
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.PAYSTATUS
     *
     * @param paystatus the value for t_payinfbyurl.PAYSTATUS
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus == null ? null : paystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.PAYMONEY
     *
     * @return the value of t_payinfbyurl.PAYMONEY
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.PAYMONEY
     *
     * @param paymoney the value for t_payinfbyurl.PAYMONEY
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.MD5STR
     *
     * @return the value of t_payinfbyurl.MD5STR
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getMd5str() {
        return md5str;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.MD5STR
     *
     * @param md5str the value for t_payinfbyurl.MD5STR
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setMd5str(String md5str) {
        this.md5str = md5str == null ? null : md5str.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.COMMODITY
     *
     * @return the value of t_payinfbyurl.COMMODITY
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.COMMODITY
     *
     * @param commodity the value for t_payinfbyurl.COMMODITY
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity == null ? null : commodity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.COMCOUNT
     *
     * @return the value of t_payinfbyurl.COMCOUNT
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public Integer getComcount() {
        return comcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.COMCOUNT
     *
     * @param comcount the value for t_payinfbyurl.COMCOUNT
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setComcount(Integer comcount) {
        this.comcount = comcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payinfbyurl.COMPRICE
     *
     * @return the value of t_payinfbyurl.COMPRICE
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public BigDecimal getComprice() {
        return comprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payinfbyurl.COMPRICE
     *
     * @param comprice the value for t_payinfbyurl.COMPRICE
     *
     * @mbggenerated Thu Jul 03 10:25:56 CST 2014
     */
    public void setComprice(BigDecimal comprice) {
        this.comprice = comprice;
    }
}