package com.ising99.wkis.parameter;


public class PlayerThemeParam extends PageBaseParam {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme.app_version_id
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Integer appVersionId;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player_theme.app_version_id
     *
     * @return the value of t_player_theme.app_version_id
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public Integer getAppVersionId() {
        return appVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player_theme.app_version_id
     *
     * @param appVersionId the value for t_player_theme.app_version_id
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    public void setAppVersionId(Integer appVersionId) {
        this.appVersionId = appVersionId;
    }


}