package com.ising99.wkis.parameter;


public class PlayerThemeMusicParam extends PageBaseParam{

    public Integer getThemeid() {
        return themeid;
    }

    public void setThemeid(Integer themeid) {
        this.themeid = themeid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player_theme_music.id
     *
     * @mbggenerated Fri Jul 04 11:15:37 CST 2014
     */
    private Integer themeid;


}