package com.ising99.wkis.parameter;

import java.util.Date;

public class TVAppDownloadInfoParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.id
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.appinfo_id
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private Integer appinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.perversion
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String perversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.version
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.name
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.wifimac
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String wifimac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.ip
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.mac
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.createtime
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.sn
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvapp_download_info.koiccode
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    private String koiccode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.id
     *
     * @return the value of tvapp_download_info.id
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.id
     *
     * @param id the value for tvapp_download_info.id
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.appinfo_id
     *
     * @return the value of tvapp_download_info.appinfo_id
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public Integer getAppinfoid() {
        return appinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.appinfo_id
     *
     * @param appinfoid the value for tvapp_download_info.appinfo_id
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setAppinfoid(Integer appinfoid) {
        this.appinfoid = appinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.perversion
     *
     * @return the value of tvapp_download_info.perversion
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getPerversion() {
        return perversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.perversion
     *
     * @param perversion the value for tvapp_download_info.perversion
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setPerversion(String perversion) {
        this.perversion = perversion == null ? null : perversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.version
     *
     * @return the value of tvapp_download_info.version
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.version
     *
     * @param version the value for tvapp_download_info.version
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.name
     *
     * @return the value of tvapp_download_info.name
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.name
     *
     * @param name the value for tvapp_download_info.name
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.wifimac
     *
     * @return the value of tvapp_download_info.wifimac
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getWifimac() {
        return wifimac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.wifimac
     *
     * @param wifimac the value for tvapp_download_info.wifimac
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setWifimac(String wifimac) {
        this.wifimac = wifimac == null ? null : wifimac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.ip
     *
     * @return the value of tvapp_download_info.ip
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.ip
     *
     * @param ip the value for tvapp_download_info.ip
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.mac
     *
     * @return the value of tvapp_download_info.mac
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.mac
     *
     * @param mac the value for tvapp_download_info.mac
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.createtime
     *
     * @return the value of tvapp_download_info.createtime
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.createtime
     *
     * @param createtime the value for tvapp_download_info.createtime
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.sn
     *
     * @return the value of tvapp_download_info.sn
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.sn
     *
     * @param sn the value for tvapp_download_info.sn
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvapp_download_info.koiccode
     *
     * @return the value of tvapp_download_info.koiccode
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public String getKoiccode() {
        return koiccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvapp_download_info.koiccode
     *
     * @param koiccode the value for tvapp_download_info.koiccode
     *
     * @mbggenerated Sat Jun 28 16:36:47 CST 2014
     */
    public void setKoiccode(String koiccode) {
        this.koiccode = koiccode == null ? null : koiccode.trim();
    }
}